# Read in on backstory
# Designed off of "Resident Evil" a Call of Cthulhu supplement

#print(f"Read_In.__name__: {__name__}")

from time import sleep

Read_In = '''In the beginning of the twenty-first century the breakthrough in genetic research and manipulation had set the battlefield for a corporate war in the medical industry,
but one corporation stands out more than the others, Umbrella Corporation.
The Umbrella Corporation had become the largest commercial entity in the United States. Nine out of ten homes contain its products.
Its political and financial influences is felt everywhere. In public it is the world's leading supplier of:

Computer Technology
Medical Products
and Health Care
However, unknown even to its own employees, its massive profits are generated by:

Military Technology
Genetic Experimentation
and Viral Weaponry
        
The Birth of a Corporation
        
In the 1950s in Raccoon City USA, Edward Ashford and Ozwell E. Spencer discovered the "Mother Virus"
during a genetical breakthrough and realized it's great potential for development of medical advancement,
but also, bio-weapons.
They began creating what would one day be known as the "T-Virus"
        
In the mid-60s Edward and Ozwell founded the company Umbrella Chemical Incorporated.
to camouflage their research and spencer had a mansion built outside Raccoon City,
so that they could continue their research without anyone knowing.
Genetical Research was still in its early stages at that time, and competition between medical companies was fierce.
To the public Umbrella Inc. was considered a very generous company
as it helped finance the city's hospital and many other things.
The public was kept in the dark about the virus research being conducted underneath it.
        
Time passed and Umbrella grew to a large corporation spanning across the entire globe
and possessing a total market share of 90 percent on computer technology, medical products, and healthcare in the US.
But their work with the T-Virus and other Bio-Organic Weapons (B.O.W.) experiments was what became Umbrella's main financial factor.

Then that all changed...

The Incident

In 1998, an accident happened at the mansion and the T-Virus was released.
It turned ordinary people into mindless zombies, and the many B.O.W.'s, which were kept in the basement,
escaped....

Raccoon City's newly formed S.T.A.R.S. (Special Tactics and Rescue Service) sent its Bravo Team to take care of the situation.
Communications were lost and Alpha Team was sent in to search for Bravo Team.
They uncovered Umbrella's virus research and had to battle their way through hordes of former researchers and other personnel
who had all been turned into bloodthirsty zombies, oversized spiders, zombie dogs, and other forms of B.O.W.'s.

Finally, they found out that their own team leader, Albert Wesker, had been acting on orders from Umbrella.
He was to gather data about the B.O.W.'s combat performance and release Umbrella's ultimate bio-weapon.
The Tyrant,
to finish off the S.T.A.R.S. Alpha Team. The Tyrant was still in early testing, and it killed Wesker before it was defeated
and the mansion was blown up along with any evidence that could connect Umbrella with the incident.

Meanwhile, Dr. William Birkin, the Umbrella top-scientist who perfected the T-Virus, continued working on the virus
and eventually developed the G-Virus.
He stayed in an underground laboratory under Raccoon City and paid the police chief to keep anyone from finding it.
However, the discovery of the G-Virus was leaked to Umbrella, and they sent a team to recover the newly discovered G-Virus.
Dr. Birkin refused to hand it over to the Umbrella operatives and they were forced to shoot him.
While his wife, Anette, went for first aid equipment.
William Birkin injected himself with the G-Virus and turned into a horrifying and powerful creature, known later as the
G-Type,
and went after the Umbrella agents. He hunted them down and killed them all.
Unfortunately, he also broke the case that contained both the T-Virus and G-Virus.
The viruses spread through the sewer system and poisoned rats, which carried the virus up to the inhabitants of Raccoon City...

Where You Come In

During these events unbeknown to you, you have come to Raccoon City for a weapons industry convention,
your ticket came with a complimentary room at the Apple Inn located near Jack's Bar,
where you had spent the evening drinking.
which is the last thing you remember before waking up in your room.
It is currently destroyed.
The furniture is tossed all over, and your dresser is in front of the door.'''

def read_in():
    for line in Read_In.splitlines():
        print(line)
        sleep(3)


if __name__ == "__main__":
    read_in()